version: '3.8'

services:

  db:
    image: bitnami/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/bitnami/mysql

  cache:
    image: redis:latest
    volumes:
      - cache_data:/data

  wordpress:
    image: bitnami/wordpress:latest
    environment:
      WORDPRESS_DATABASE_HOST:  ${WORDPRESS_DATABASE_HOST}
      WORDPRESS_DATABASE_NAME: ${WORDPRESS_DATABASE_NAME}
      WORDPRESS_DATABASE_USER: ${WORDPRESS_DATABASE_USER}
      WORDPRESS_DATABASE_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD}
      WORDPRESS_CACHE_HOST: ${WORDPRESS_CACHE_HOST}
      WORDPRESS_CACHE_PORT_NUMBER: ${WORDPRESS_CACHE_PORT_NUMBER}
      WORDPRESS_CACHE_USE_REDIS: ${WORDPRESS_CACHE_USE_REDIS}
    ports:
      - "8080:8080"
    volumes:
      - wordpress_data:/bitnami/wordpress
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress

volumes:
  db_data:
  cache_data:
  wordpress_data:
